server:
  servlet:
    context-path: /api
spring:
  application:
    name: cosy-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/cosy
    username: cosy
    password: cosy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE
jwt:
  secret-key: ${COSY_JWT_SECRET_KEY:e8996bf24977ce5615015c717447911799207025d1998a01256b7b7717bac18e} #change in prod
  identity-token-expiration-time: 3600000 #1 hour
  refresh-token-expiration-time: 2678400000 #1 month
management:
  endpoints:
    web:
      exposure:
        include: "health,readiness,liveness"
cosy:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - https://cosy.jannekeipert.de
  engine:
    selected: DOCKER

    # Docker-specific configuration
    docker:
      socket-path: "npipe:////./pipe/docker_engine"  # Docker socket
      api-version: "1.41"                       # Optional: API version
      tls: false                                # Whether to use TLS
      cert-path: ""                             # Path to TLS certs if enabled

    # Kubernetes-specific configuration
    kubernetes:
      kubeconfig: "C:/Users/fiete/.kube/config" # Path to kubeconfig file
      context: "docker-desktop"                 # Docker Desktop Kubernetes context
      namespace: "default"                      # Namespace to operate in
      in-cluster: false                         # Backend runs on host, not in cluster
      timeout-seconds: 30                       # Request timeout (seconds)

      labels: # Default labels added to all pods
        app: cosy
        platform: docker-desktop
