server:
  servlet:
    context-path: /api
spring:
  application:
    name: cosy-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/cosy
    username: cosy
    password: cosy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE
jwt:
  secret-key: e8996bf24977ce5615015c717447911799207025d1998a01256b7b7717bac18e #change in prod
  identity-token-expiration-time: 3600000 #1 hour
  refresh-token-expiration-time: 2678400000 #1 month
management:
  endpoints:
    web:
      exposure:
        include: "health,readiness,liveness"
cosy:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - https://cosy.jannekeipert.de
